spring:
  application:
    name: application-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/administration/templates/

server:
  port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
